### ISSUE TITLE
Make labels and h3 more generic

### ISSUE THREAD

**Issue by zeljko-djuric** [zeljko-djuric/adverity-coding-challenge#1]
`<h3>Choose channel or campaign:</h3>`
`<label>Clicks: </label>`
`<label>Impressions: </label>`

Change this hardcoded solution with a more generic. Attribute values should be passed from the main **App.js** component.

**Comment by vlabs** [comment]
this should be a simple reusable functional component, eg `MetricValue`. what would be the props?
