### ISSUE TITLE
Rewrite calculateClicksAndImpressions as a pure function

### ISSUE THREAD

**Issue by zeljko-djuric** [zeljko-djuric/adverity-coding-challenge#2]
Function calculateClicksAndImpressions is doing too many things and has side effects. `const selectedSuggestion` and `const rawData` should be passed as arguments. Also, the function implementation could be replaced into the App.js component.

- This code should be generic

```
this.state = {
      suggestions: [],
      clicks: 0,
      impressions: 0
    };
```
```
this.setState({
      clicks: totalClicks,
      impressions: totalImpressions
    });
```

**Comment by vlabs** [comment]
please put into a separate folder and file (eg `src/utils/calculateClicksAndImpressions`) and then you should also create tests for this function.

i would call the arguments `campaignOrChannel` and simply `data`
