### ISSUE TITLE
Fix suggestions for Select input

### ISSUE THREAD

**Issue by zeljko-djuric** [zeljko-djuric/adverity-coding-challenge#3]
- `const selectSuggestions = _.uniqWith(this.state.suggestions, _.isEqual)` 
When channel and campaign are the same with this solution it will remove one of them.

- ```props.dataCSV.data.forEach((element, i) => {
      this.setState((state, props) => ({
        suggestions: [
          ...state.suggestions,
          { label: props.dataCSV.data[i].campaign },
          { label: props.dataCSV.data[i].channel }
        ]
      }));
 It could be better to have suggestions for channels and campaigns separately.

**Comment by vlabs** [comment]
code pointers are also quite cool in gihub:
https://github.com/zeljko-djuric/adverity-coding-challenge/blob/38cca8cfbe5aea4676b0fd7576136aa3c79ee492/src/components/DisplayMetrics.js#L71
